services:
  db:
    image: postgres:15-alpine
    container_name: sentinela_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_sentinela
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - maas-network

  ingestor:
    build: .
    container_name: sentinela_ingestor
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - /dev/shm:/dev/shm
      - ../proto:/app/proto:ro
      - ./src:/app/src
    networks:
      - default
      - maas-network
    command: python src/ingestor.py

  processor:
    build: .
    container_name: sentinela_processor
    restart: always
    depends_on:
      db:
        condition: service_healthy
      ingestor:
        condition: service_started
    env_file:
      - .env
    volumes:
      - /dev/shm:/dev/shm
      - ../proto:/app/proto:ro
      - ./src:/app/src
    networks:
      - maas-network
    command: python src/data_processor.py

  ai_processor:
    build: .
    container_name: sentinela_ai
    restart: always
    depends_on:
      db:
        condition: service_healthy
      processor:
        condition: service_started
    env_file:
      - .env
    volumes:
      - /dev/shm:/dev/shm
      - ../proto:/app/proto:ro
      - ./src:/app/src
      - ./models:/app/models:ro
    networks:
      - maas-network
    command: python src/ai_processor.py

  dashboard:
    build: .
    container_name: sentinela_dashboard
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ../proto:/app/proto:ro
      - ./src:/app/src
      - ./static:/app/static:ro
    ports:
      - "8000:8000"
    networks:
      - maas-network
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000

networks:
  maas-network:
    name: maas-network
    driver: bridge

volumes:
  postgres_data:
